const propertyList = [
  {
    id: 1,
    title: "4 BHK Ultra-Luxury Apartment",
    location: "Geeta Bhawan, Indore",
    price: 31500000,
    pricePerSqFt: 7500,
    type: "Buy",
    bhk: "4 BHK",
    area: 4200,
    verified: true,
    parking: true,
    bathrooms: 4,
    propertyType: "Apartment",

    furnishing: "Luxury",
    balcony: true,
    servantRoom: true,
    construction: "Premium",
    description:
      "Spacious 4 BHK ultra-luxurious apartment with large balcony and servant room. Located in prime city centre Geeta Bhawan, perfect for families seeking luxury living.",
    city: "Indore",
    state: "Madhya Pradesh",
    listingType: "Luxury",
    contact: true,

    // ⭐ Key Highlights
    keyHighlights: [
      "Spacious layout with large balcony",
      "Servant room for added convenience",
      "Premium construction & elegant design",
      "Located in the prime city centre – Geeta Bhawan",
    ],

    images: [
      "/propertyList/property1/img1.jpeg",
      "/propertyList/property1/img2.jpeg",
      "/propertyList/property1/img3.jpeg",
      "/propertyList/property1/img4.jpeg",
      "/propertyList/property1/img5.jpeg",
      "/propertyList/property1/img6.jpeg",
      "/propertyList/property1/img7.jpeg",
      "/propertyList/property1/img8.jpeg",
      "/propertyList/property1/img9.jpeg",
      "/propertyList/property1/img10.jpeg",
      "/propertyList/property1/img11.jpeg",
      "/propertyList/property1/img12.jpeg",
      "/propertyList/property1/img13.jpeg",
      "/propertyList/property1/img14.jpeg",
      "/propertyList/property1/img15.jpeg",
      "/propertyList/property1/img16.jpeg",
      "/propertyList/property1/img17.jpeg",
    ],

    // 📄 PDF Layout
    floorPlan: {
      image: "/propertyList/property1/floorplan.png", // converted image from PDF
      pdf: "/pdfs/vidhya-tower-2.pdf", // original PDF
    },
  },
  {
    id: 2,
    title: "Modern Sky Apartment",
    location: "AB Road, Indore",
    price: 25000,
    type: "Rent",
    bhk: "2 BHK",
    area: 1200,
    verified: true,
    parking: true,
    bathrooms: 2,
    propertyType: "Apartment",
  },
  {
    id: 3,
    title: "Prime Office Space",
    location: "Sapna Sangeeta, Indore",
    price: 45000,
    type: "Commercial",
    bhk: "Commercial",
    area: 1800,
    verified: false,
    parking: true,
    bathrooms: 2,
    propertyType: "Office",
  },
  {
    id: 4,
    title: "Green Valley Residential Plot",
    location: "Super Corridor, Indore",
    price: 3500000,
    type: "Plot",
    bhk: "Plot",
    area: 2000,
    verified: true,
    parking: false,
    bathrooms: 0,
    propertyType: "Plot",
  },
  {
    id: 5,
    title: "Cozy Studio Apartment",
    location: "Palasia, Indore",
    price: 12000,
    type: "Rent",
    bhk: "1 BHK",
    area: 600,
    verified: true,
    parking: false,
    bathrooms: 1,
    propertyType: "Apartment",
  },
  {
    id: 6,
    title: "Royal Penthouse Suite",
    location: "South Tukoganj, Indore",
    price: 15000000,
    type: "Buy",
    bhk: "5+ BHK",
    area: 3500,
    verified: true,
    parking: true,
    bathrooms: 4,
    propertyType: "Apartment",
  },
  {
    id: 7,
    title: "Spacious Family Flat",
    location: "Nipania, Indore",
    price: 18000,
    type: "Rent",
    bhk: "3 BHK",
    area: 1500,
    verified: false,
    parking: true,
    bathrooms: 2,
    propertyType: "Apartment",
  },
  {
    id: 8,
    title: "Premium Retail Shop",
    location: "MG Road, Indore",
    price: 35000,
    type: "Commercial",
    bhk: "Commercial",
    area: 900,
    verified: true,
    parking: false,
    bathrooms: 1,
    propertyType: "Shop",
  },
  {
    id: 9,
    title: "Elegant Duplex House",
    location: "Scheme 54, Indore",
    price: 12000000,
    type: "Buy",
    bhk: "4 BHK",
    area: 2800,
    verified: true,
    parking: true,
    bathrooms: 3,
    propertyType: "House",
  },
  {
    id: 10,
    title: "Budget Friendly Apartment",
    location: "Rau, Indore",
    price: 8000,
    type: "Rent",
    bhk: "1 BHK",
    area: 500,
    verified: false,
    parking: false,
    bathrooms: 1,
    propertyType: "Apartment",
  },
  {
    id: 11,
    title: "Commercial Hub Plot",
    location: "Bypass Road, Indore",
    price: 8000000,
    type: "Plot",
    bhk: "Plot",
    area: 5000,
    verified: true,
    parking: false,
    bathrooms: 0,
    propertyType: "Plot",
  },
  {
    id: 12,
    title: "Premium Treasure Apartment",
    location: "Treasure Island, Indore",
    price: 9500000,
    type: "Buy",
    bhk: "3 BHK",
    area: 1800,
    verified: true,
    parking: true,
    bathrooms: 2,
    propertyType: "Apartment",
  },
  {
    id: 13,
    title: "Sunrise Villa Estate",
    location: "Bengali Square, Indore",
    price: 11000000,
    type: "Buy",
    bhk: "5+ BHK",
    area: 3200,
    verified: true,
    parking: true,
    bathrooms: 4,
    propertyType: "Villa",
  },
  {
    id: 14,
    title: "Modern Office Tower",
    location: "Vijay Nagar, Indore",
    price: 65000,
    type: "Commercial",
    bhk: "Commercial",
    area: 2500,
    verified: true,
    parking: true,
    bathrooms: 3,
    propertyType: "Office",
  },
  {
    id: 15,
    title: "Compact Studio",
    location: "Race Course Road, Indore",
    price: 10000,
    type: "Rent",
    bhk: "1 BHK",
    area: 450,
    verified: true,
    parking: false,
    bathrooms: 1,
    propertyType: "Apartment",
  },
  {
    id: 16,
    title: "Luxury Bungalow",
    location: "New Palasia, Indore",
    price: 18000000,
    type: "Buy",
    bhk: "5+ BHK",
    area: 4000,
    verified: true,
    parking: true,
    bathrooms: 5,
    propertyType: "House",
  },
  {
    id: 17,
    title: "Garden View Apartment",
    location: "Sukhliya, Indore",
    price: 22000,
    type: "Rent",
    bhk: "2 BHK",
    area: 1100,
    verified: true,
    parking: true,
    bathrooms: 2,
    propertyType: "Apartment",
  },
  {
    id: 18,
    title: "Business Plaza Shop",
    location: "Treasure Island, Indore",
    price: 28000,
    type: "Commercial",
    bhk: "Commercial",
    area: 800,
    verified: false,
    parking: true,
    bathrooms: 1,
    propertyType: "Shop",
  },
  {
    id: 19,
    title: "Agricultural Land Plot",
    location: "Mhow, Indore",
    price: 2500000,
    type: "Plot",
    bhk: "Plot",
    area: 10000,
    verified: true,
    parking: false,
    bathrooms: 0,
    propertyType: "Plot",
  },
  {
    id: 20,
    title: "Executive Apartment",
    location: "AB Road, Indore",
    price: 30000,
    type: "Rent",
    bhk: "3 BHK",
    area: 1600,
    verified: true,
    parking: true,
    bathrooms: 2,
    propertyType: "Apartment",
  },
];

export default propertyList;

// ✨ Luxury Living in the Heart of Indore ✨

// 4 BHK Ultra-Luxurious Apartment available for sale at Vibrant Vidhya Palace, Geeta Bhawan – Indore

// 🏡 Size: 4200 Sq. Ft.
// 💰 Demand: ₹7,500 / Sq. Ft.

// Key Highlights:
// * Spacious layout with large balcony
// * Servant room for added convenience
// * Premium construction & elegant design
// * Located in the prime city centre – Geeta Bhawan

// Perfect for families looking for luxury, space & prime location.

// 📞 For details & site visit, connect with me
